services:

  postgres:
    image: postgres:16
    container_name: postgres-climas

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: clima_db

    ports:
      - "5432:5432"

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow

    container_name: airflow-clima

    depends_on:
      - postgres

    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db

      # Usuário e senha do Airflow
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin123

      # Variáveis usadas pelo pipeline
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_JDBC_URL: jdbc:postgresql://postgres:5432/clima_db?sslmode=disable

    ports:
      - "8081:8080"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/project/src
      - ./data:/opt/airflow/project/data

    command: standalone